services:
  postgres:
    image: bitnami/postgresql:15.10.0
    restart: on-failure

    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: my-secure-password
      POSTGRESQL_DATABASE: backend
      POSTGRESQL_TIMEZONE: America/Sao_Paulo

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
